# Generated by Django 3.0.3 on 2020-02-05 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20200204_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1e9b3a59-bc0e-4762-a714-0b558af84743'), editable=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1e9b3a59-bc0e-4762-a714-0b558af84743'), editable=False),
        ),
    ]
